---
- name: NXOS VLAN configuration
  hosts: nxos
  gather_facts: no

  tasks:

  #############################################################
  # Layer 2 switchport configs
  #############################################################
  - name: L2 config for uplinks
    nxos_interface:
      aggregate: "{{l2_ports}}"
      mode: layer2
      admin_state: up

  - name: Trunk config for uplinks
    nxos_l2_interface:
      aggregate: "{{trunk_ports}}"
