---
- name: Show Version Long
  hosts: all
  gather_facts: no

  tasks:

  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: display current IOS version
    debug:
      var: ansible_net_version
      
