# Copyright (c) 2018 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.0 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
#
# AUTHOR(s): Eric Thiel <erthiel@cisco.com>

---
- name: NETCONF sample 1
  hosts: iosxe
  connection: local
  gather_facts: False

  tasks:

    - set_fact:
        ansible_connection: local

    - name: Delete a loopback with NETCONF
      netconf_config:
        host: "{{inventory_hostname}}"
        port: "{{netconf_port}}"
        username: "{{ansible_username}}"
        password: "{{ansible_password}}"
        hostkey_verify: False
        xml: |
            <config>
              <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
                <interface operation="delete">
                  <name>Loopback1{{pod_number}}</name>
                </interface>
              </interfaces>
            </config>
