ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_network_os: ios

local_vrfs:
  - name: red
    description: "Red VRF"
    rd: "1:100"
  - name: blue
    description: "Blue VRF"
    rd: "1:110"
  - name: green
    description: "Green VRF"
    rd: "1:120"
  - name: "{{user_pod}}"
    description: "{{user_pod}} VRF"
    rd: "1:{{pod_number}}"